### ISSUE TITLE
Exception because of letsencrypt/client/apache/options-ssl.conf missing

### ISSUE THREAD

**Issue by JensErat** [letsencrypt/lets-encrypt-preview#150]
When I try to run `letsencrypt` for a pretty much barebone setup (Ubuntu 14.04 inside a Docker container, with an Apache configured for `www.example.com`, thus only the host line commented out in the default vhost and not reachable from the Internet), it fails after this screen:

    Generating key: /etc/apache2/ssl/key-letsencrypt_1.pem  
    Creating CSR: /etc/apache2/certs/csr-letsencrypt_1.pem  
    Starting new HTTPS connection (1): letsencrypt-demo.org 
    Performing the following challenges:                    
      DVSNI challenge for name www.example.com.             
    Created an SSL vhost at                                 
    /etc/apache2/sites-available/000-default-le-ssl.conf 

with following traaceback:

    Traceback (most recent call last):
      File "./venv/bin/letsencrypt", line 9, in <module>
        load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
      File "/opt/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/scripts/main.py", line 127, in main
        cert_file, chain_file = acme.obtain_certificate(csr)
      File "/opt/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/client.py", line 82, in obtain_certificate
        responses, challenge_objs = self.verify_identity(challenge_msg)
      File "/opt/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/client.py", line 286, in verify_identity
        resp = self.auth.perform(c_obj)
      File "/opt/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/apache/configurator.py", line 944, in perform
        return self.dvsni_perform(chall_dict)
      File "/opt/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/apache/configurator.py", line 1007, in dvsni_perform
        addresses)
      File "/opt/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/apache/configurator.py", line 1049, in dvsni_mod_config
        shutil.copyfile(dist_conf, CONFIG.OPTIONS_SSL_CONF)
      File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
        with open(src, 'rb') as fsrc:
    IOError: [Errno 2] No such file or directory: '/opt/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/apache/options-ssl.conf'

I guess this is a problem with a non-verifiable domain, but I didn't test yet with a proper hostname and connect to the internet. Anyway, at least a better error message should be printed.

**Comment by jdkasten** [comment]
It actually seems to be a problem with packaging.  options-ssl.conf is the file included in the ssl-vhost configuration to provide good defaults for ciphers/protocols ect...

We temporarily added a cp options-ssl.conf to CONFIG.py's CONFIG_DIR if the file did not exist for testing purposes. (This will be removed as we get closer to launch)

I restructured the code into a new apache directory... but it looks like I may have broken this temporary copy.

You should be able to fix the problem if you move the options-ssl.conf file into /etc/letsencrypt/ 

I believe this is the incorrect line.
https://github.com/letsencrypt/lets-encrypt-preview/blob/master/letsencrypt/client/apache/configurator.py#L1046

I will issue a patch here shortly moving options-ssl.conf from the letsencrypt/client/ directory to the letsencrypt/client/apache directory since it is an apache config file.

Thanks for the bug report!

**Comment by jdkasten** [comment]
I was able to recreate the error and believe I have addressed it with the latest commit. You mentioned using a name that wasn't globally addressable in your testing setup.  Our testing server still won't be able to verify your challenges.

If you would like, I can modify our testing server to point to a domain of your choosing in order to aid in testing/development.  (something with the TLD .demo)

**Comment by JensErat** [comment]
I can verify the issue being fixed for my setup. Just wasn't ready yet to move to some host with unused http(s) ports, which is my next step.
