### ISSUE TITLE
traceback in x509v3_ext_conf

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsencrypt/lets-encrypt-preview#224]
command: sudo letsencrypt -t

then selected 1 for first (and only) domain it found, then boom:

Traceback (most recent call last):
  File "./venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/scripts/main.py", line 133, in main
    cert_file, chain_file = acme.obtain_certificate(domains)
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/client/client.py", line 98, in obtain_certificate
    self.auth_handler.get_authorizations()
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/client/auth_handler.py", line 79, in get_authorizations
    self._satisfy_challenges()
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/client/auth_handler.py", line 153, in _satisfy_challenges
    dv_resp = self.dv_auth.perform(flat_auth)
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/client/apache/configurator.py", line 992, in perform
    sni_response = apache_dvsni.perform()
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/client/apache/dvsni.py", line 90, in perform
    s_b64 = self._setup_challenge_cert(chall)
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/client/apache/dvsni.py", line 108, in _setup_challenge_cert
    chall.domain, chall.r_b64, chall.nonce, chall.key)
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/client/challenge_util.py", line 54, in dvsni_gen_cert
    key.pem, [nonce + CONFIG.INVALID_EXT, name, ext])
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/client/crypto_util.py", line 214, in make_ss_cert
    'subjectAltName', ", ".join(["DNS:%s" % d for d in domains])))
  File "/home/tw/w/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/M2Crypto/X509.py", line 32, in new_extension
    x509_ext_ptr = m2.x509v3_ext_conf(lhash, ctx, name, value)
TypeError: in method 'x509v3_ext_conf', argument 4 of type 'char *'

**Comment by jdkasten** [comment]
Thanks @ThomasWaldmann I was able to confirm.  (text mode hasn't been tested too much, but display/revoker is my current PR) It must be something with the return value of the display filter_names because specifying the domain with -d works.

**Comment by jdkasten** [comment]
This has been fixed.  Thanks @ThomasWaldmann!

**Comment by mcepl** [comment]
@jdkasten  can I ask HOW was this fixed? I am a maintainer of M2Crypto, so I would like to know, whether there is something we do wrong, or whether we can improve (rather awful) error message for this sitaution. Thank you.

**Comment by kaizengliu** [comment]
May be because the value ["DNS:%s" % d for d in domain] is unicode, an the argument value of  `x509v3_ext_conf(lhash, ctx, name, value)` must be string.

**Comment by mcepl** [comment]
> May be because the value ["DNS:%s" % d for d in domain] is unicode,

It is truly ``unicode``? We are talking about Python 2.* here, so there is no really difference between ``str`` and ``bytes``.

**Comment by kaizengliu** [comment]
Yes, I met the same problem, and found when the value is `str`, it is good,   and `unicode` gets the error always.

**Comment by mcepl** [comment]
OK, then I call it a non-M2Crypto bug: [X509.new_extension](https://gitlab.com/m2crypto/m2crypto/blob/master/M2Crypto/X509.py#L38) calls for ``str`` and ``bytes`` as types of the first parameters respectively, and although I may add an ``assert`` there, I probably won’t unless otherwise persuaded.
