### ISSUE TITLE
traceback when cancelling domain selection

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsencrypt/lets-encrypt-preview#225]
sudo letsencrypt -t
cancel domain selection, boom:

Traceback (most recent call last):
  File "./venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/scripts/main.py", line 115, in main
    domains = choose_names(installer) if args.domains is None else args.domains
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/scripts/main.py", line 158, in choose_names
    interfaces.IDisplay).filter_names(get_all_names(installer))
  File "/home/tw/w/lets-encrypt-preview/letsencrypt/client/display.py", line 300, in filter_names
    return code, [names[tag]]
IndexError: list index out of range

**Comment by jdkasten** [comment]
Thanks @ThomasWaldmann! I am currently refactoring all of the display code... I will make sure to fix this bug

**Comment by jdkasten** [comment]
I see that you fixed the specific bug... I will pull it into master if it is ready

**Comment by ThomasWaldmann** [comment]
ok.

**Comment by jdkasten** [comment]
This has been fixed.  Thanks @ThomasWaldmann!
