### ISSUE TITLE
ReadTheDocs doesn't render some API pages

### ISSUE THREAD

**Issue by kuba** [letsencrypt/lets-encrypt-preview#262]
For the following API pages the generated output is empty:
- http://letsencrypt.readthedocs.org/en/latest/api/client/augeas_configurator.html
- http://letsencrypt.readthedocs.org/en/latest/api/client/client.html

It works locally though...

**Comment by kuba** [comment]
http://letsencrypt.readthedocs.org/en/latest/api/client/apache.html#letsencrypt-client-apache-configurator is broken as well

https://readthedocs.org/builds/letsencrypt/2262458/:
```
html
-----

/var/build/user_builds/letsencrypt/checkouts/latest/docs/api/client/apache.rst:10: WARNING: autodoc: failed to import module u'letsencrypt.client.apache.configurator'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/apache/configurator.py", line 13, in <module>
    from letsencrypt.client import augeas_configurator
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/augeas_configurator.py", line 4, in <module>
    import augeas
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/python_augeas-0.5.0-py2.7.egg/augeas.py", line 78, in <module>
    class Augeas(object):
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/python_augeas-0.5.0-py2.7.egg/augeas.py", line 82, in Augeas
    _libaugeas = _dlopen("augeas")
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/python_augeas-0.5.0-py2.7.egg/augeas.py", line 75, in _dlopen
    raise ImportError("Unable to import lib%s!" % args[0])
ImportError: Unable to import libaugeas!
/var/build/user_builds/letsencrypt/checkouts/latest/docs/api/client/augeas_configurator.rst:4: WARNING: autodoc: failed to import module u'letsencrypt.client.augeas_configurator'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/augeas_configurator.py", line 4, in <module>
    import augeas
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/python_augeas-0.5.0-py2.7.egg/augeas.py", line 78, in <module>
    class Augeas(object):
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/python_augeas-0.5.0-py2.7.egg/augeas.py", line 82, in Augeas
    _libaugeas = _dlopen("augeas")
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/python_augeas-0.5.0-py2.7.egg/augeas.py", line 75, in _dlopen
    raise ImportError("Unable to import lib%s!" % args[0])
ImportError: Unable to import libaugeas!
/var/build/user_builds/letsencrypt/checkouts/latest/docs/api/client/client.rst:4: WARNING: autodoc: failed to import module u'letsencrypt.client.client'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/client.py", line 24, in <module>
    from letsencrypt.client.apache import configurator
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/apache/configurator.py", line 13, in <module>
    from letsencrypt.client import augeas_configurator
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/augeas_configurator.py", line 4, in <module>
    import augeas
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/python_augeas-0.5.0-py2.7.egg/augeas.py", line 78, in <module>
    class Augeas(object):
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/python_augeas-0.5.0-py2.7.egg/augeas.py", line 82, in Augeas
    _libaugeas = _dlopen("augeas")
  File "/home/docs/checkouts/readthedocs.org/user_builds/letsencrypt/envs/latest/local/lib/python2.7/site-packages/python_augeas-0.5.0-py2.7.egg/augeas.py", line 75, in _dlopen
    raise ImportError("Unable to import lib%s!" % args[0])
ImportError: Unable to import libaugeas!
../README.rst:None: WARNING: nonlocal image URI found: https://travis-ci.org/letsencrypt/lets-encrypt-preview.svg?branch=master
```

**Comment by jdkasten** [comment]
Unfortunately, the patch didn't fully solve the problem.  I didn't find any errors in the build log, (did a quick search) but I know interfaces.py and client.py at least are still not resolving correctly on readthedocs.  (Both seem to work perfectly well locally).  I have been temporarily pointing people towards interfaces.py itself as that documentation is probably the most important bit in the project.

**Comment by kuba** [comment]
Thanks. I'll look into that later.

**Comment by kuba** [comment]
Actually, I experienced the problem myself until... I hit Ctrl+F5. Some heavy caching going out there! Could you try it, @jdkasten?

**Comment by jdkasten** [comment]
Geez... it was a caching issue. I apologize. Thanks!
