### ISSUE TITLE
DvsniPerformTest errors

### ISSUE THREAD

**Issue by kuba** [letsencrypt/lets-encrypt-preview#316]
Interestingly, Travis is green, but locally I get the following errors:

```
======================================================================
FAIL: test_mod_config (letsencrypt.client.tests.apache.dvsni_test.DvsniPerformTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jakub/dev/letsencrypt/lets-encrypt-preview/letsencrypt/client/tests/apache/dvsni_test.py", line 156, in test_mod_config
    self.assertEqual(len(vhs), 2)
AssertionError: 0 != 2
-------------------- >> begin captured logging << --------------------
root: DEBUG: Creating backup of /tmp/tmpXgEs3Stemp/debian_apache_2_4/two_vhost_80/apache2/apache2.conf
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_perform0 (letsencrypt.client.tests.apache.dvsni_test.DvsniPerformTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jakub/dev/letsencrypt/lets-encrypt-preview/letsencrypt/client/tests/apache/dvsni_test.py", line 63, in test_perform0
    self.assertTrue(resp is None)
AssertionError: False is not true
```

It seems like #286 broke it.

**Comment by kuba** [comment]
Okay, submitted a patch. But I'm still worried why Travis didn't catch it... Merge problem?
