### ISSUE TITLE
Produce sensible error states

### ISSUE THREAD

**Issue by pde** [letsencrypt/lets-encrypt-preview#349]
Often, we'll just crash with an unhelpful traceback, rather than telling the user what went wrong in a friendly manner.  For instance, if running the <tt>boulder</tt> apache client from behind a firewall, I get this crash:

```
Traceback (most recent call last):
  File "/usr/local/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/scripts/main.py", line 214, in main
    cert_file, chain_file = acme.obtain_certificate(doms)
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/client.py", line 134, in obtain_certificate
    domains, self.regr.new_authzr_uri)
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/auth_handler.py", line 69, in get_authorizations
    domain, new_authz_uri)
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/network2.py", line 279, in request_domain_challenges
    typ=messages2.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/network2.py", line 260, in request_challenges
    response = self._post(new_authzr_uri, self._wrap_in_jws(new_authz))
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/network2.py", line 143, in _post
    self._check_response(response, content_type=content_type)
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/network2.py", line 92, in _check_response
    raise messages2.Error.from_json(jobj)
letsencrypt.acme.messages2.Error
```

**Comment by pde** [comment]
These error cases should extract a reason, and call out to the display plugin to present it.
