### ISSUE TITLE
Lets-encrypt crashes when using an IInstaller plugin

### ISSUE THREAD

**Issue by e00E** [letsencrypt/lets-encrypt-preview#471]
```
Traceback (most recent call last):
  File "./lets-encrypt-preview/venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/home/e/icecast/lets-encrypt-preview/letsencrypt/cli.py", line 403, in main
    return args.func(args, config, plugins)
  File "/home/e/icecast/lets-encrypt-preview/letsencrypt/cli.py", line 150, in install
    acme.deploy_certificate(doms, acc.key, args.cert_path, args.chain_path)
  File "/home/e/icecast/lets-encrypt-preview/letsencrypt/client.py", line 272, in deploy_certificate
    os.path.abspath(privkey_path), chain_path)
  File "/home/e/icecast/lets-encrypt-preview/venv/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/home/e/icecast/lets-encrypt-preview/venv/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'Key' object has no attribute 'startswith'
 ```
To me it seems like this happens because deploy_certificate(self, domains, privkey_path, cert_path, chain_path) in client.py expects a string for privkey_path as per contract but receives a letsencrypt.le_util.Key instead in install(args, config, plugins) at cli.py +150:
```
acme.deploy_certificate(doms, acc.key, args.cert_path, args.chain_path)
```
I fixed it locally by changing it to acc.key.file:
```
acme.deploy_certificate(doms, acc.key.file, args.cert_path, args.chain_path)
```
This is Divayth from irc by the way.

**Comment by kuba** [comment]
Hey :) Thanks for reporting. Your fix seems to be correct, would you mind sending a PR?

**Comment by e00E** [comment]
Here it is https://github.com/letsencrypt/lets-encrypt-preview/pull/475

**Comment by kuba** [comment]
@e00E, now that #475 is pulled in, can you close this bug report, please?
