### ISSUE TITLE
Unable to read/verify body

### ISSUE THREAD

**Issue by berenddeschouwer** [letsencrypt/lets-encrypt-preview#507]
When running letsencrypt auth I get the cryptic error message:

>
Error: {u'type': u'urn:acme:error:malformed', u'detail': u'Unable to read/verify body'}
Response from server: {"type":"urn:acme:error:malformed","detail":"Unable to read/verify body"}

Background: I have moved to a different DNS provider after issue #503 

It's getting further, I think.  I'm not sure *what* it's trying to read or verify.

>
Traceback (most recent call last):
  File "/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/cli.py", line 406, in main
    return args.func(args, config, plugins)
  File "/usr/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/cli.py", line 133, in auth
    plugins):
  File "/usr/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client.py", line 206, in obtain_and_enroll_certificate
    cert, privkey, chain = self.obtain_certificate(domains, csr)
  File "/usr/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client.py", line 154, in obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/usr/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/auth_handler.py", line 69, in get_authorizations
    domain, self.account.new_authzr_uri)
  File "/usr/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/network2.py", line 333, in request_domain_challenges
    typ=messages2.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/usr/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/network2.py", line 314, in request_challenges
    response = self._post(new_authzr_uri, new_authz)
  File "/usr/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/network2.py", line 179, in _post
    self._check_response(response, content_type=content_type)
  File "/usr/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/network2.py", line 101, in _check_response
    raise messages2.Error.from_json(jobj)
acme.messages2.Error: malformed :: The request message was malformed :: Unable to read/verify body

**Comment by jcjones** [comment]
I wonder if this is due to loss of state in account information that happened yesterday (long story, but it's a test server!). @kuba and I have talked and think you should try removing your `/etc/letsencrypt/accounts` directory to force a re-registration.

**Comment by berenddeschouwer** [comment]
I know it's a test server, and my expectations match that :)

It's going live soon.  I'm very curious.  I thought I'd test and file bugs.  Illegible error codes are bugs.  (I can read JSON and Python exceptions: it's still a bug :)

I'm running it on a test server that happens to need https, and it was openssl self-signed shoot-myself or this.

It gets further after rm -rf /accounts.

Now auth finishes.  'run' says  'Configurator could not be determined'.  This is legible.  Funnily this one is command-line, not python-dialog.  I'll go read the docs.

It should find 'Apache/mod_nss', but I can try 'Apache/mod_ssl'.

**Comment by jdkasten** [comment]
Apache still needs quite a bit of work... and it will not find/use mod_nss right now.

**Comment by berenddeschouwer** [comment]
I'm going to close this because the original report was triggered by a mismatch of 'accounts/' between the letsencrypt client and a test server [reload/upgrade?]
