### ISSUE TITLE
Running the demo code on Debian Wheezy 7.6

### ISSUE THREAD

**Issue by ratskrone** [letsencrypt/lets-encrypt-preview#68]
Hi everybody,
I tried the demo code for Ubuntu but on a Debian test server When hitting "./venv/bin/letsencrypt", I got the following in return. Is that return because of the unstable Apache2 conf layout? Anyhow, is there another way to test letsencrypt on Debian?

Traceback (most recent call last):
  File "./venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/home/stefan/lets-encrypt-preview-master/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/stefan/lets-encrypt-preview-master/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/home/stefan/lets-encrypt-preview-master/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/stefan/lets-encrypt-preview-master/venv/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/scripts/main.py", line 7, in <module>
    from letsencrypt.client import apache_configurator
  File "/home/stefan/lets-encrypt-preview-master/venv/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/apache_configurator.py", line 13, in <module>
    from letsencrypt.client import augeas_configurator
  File "/home/stefan/lets-encrypt-preview-master/venv/local/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/client/augeas_configurator.py", line 6, in <module>
    import augeas
  File "/home/stefan/lets-encrypt-preview-master/venv/local/lib/python2.7/site-packages/python_augeas-0.5.0-py2.7.egg/augeas.py", line 78, in <module>
    class Augeas(object):
  File "/home/stefan/lets-encrypt-preview-master/venv/local/lib/python2.7/site-packages/python_augeas-0.5.0-py2.7.egg/augeas.py", line 82, in Augeas
    _libaugeas = _dlopen("augeas")
  File "/home/stefan/lets-encrypt-preview-master/venv/local/lib/python2.7/site-packages/python_augeas-0.5.0-py2.7.egg/augeas.py", line 75, in _dlopen
    raise ImportError("Unable to import lib%s!" % args[0])
ImportError: Unable to import libaugeas!

**Comment by ThomasWaldmann** [comment]
@ratskrone did you run letsencrypt as root when it failed to used apache2ctl?

**Comment by ratskrone** [comment]
Today I ran the following instructions:

sudo apt-get install python python-setuptools python-virtualenv python-dev \
             gcc swig dialog libaugeas0 libssl-dev ca-certificates

virtualenv --no-site-packages -p python2 venv
./venv/bin/python setup.py install
sudo ./venv/bin/letsencrypt

I am running the following machine:

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

Linux x200 3.16.0 #1 SMP Wed Aug 6 00:31:37 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux

The installation routine ended with the following output:

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -c _configtest.c -o _configtest.o
success!
removing: _configtest.c _configtest.o
c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
                 ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

So, what does that mean? Installation went fine but cleaning went wrong?

**Comment by ThomasWaldmann** [comment]
you need libffi-dev package I guess.

**Comment by kuba** [comment]
What would "liffi-dev" be for, i.e. which package fails to compile? That's not listed anywhere in https://letsencrypt.readthedocs.org/en/latest/using.html#prerequisites, so we should probably add it if it is indeed necessary.

**Comment by jdkasten** [comment]
I tried to add it in #240   (I will investigate).  I believe it is required for PyOpenSSL which the standalone authenticator is currently using.  In the future I would really like to switch everything over to cryptography #164. (Which should be the base of both PyOpenSSL and PyCrypto)

**Comment by ratskrone** [comment]
Thx. Installing libffi-dev solved the posted issue. I will try it out next. Cu

**Comment by kuba** [comment]
@ratskrone any updates on this? if it's works, please close the issue, thanks!

**Comment by ratskrone** [comment]
I am done. My issue is solved.
